import { Job, Company, Category } from "@/types";

export const JOBS: Job[] = [
  {
    _id: "1",
    title: "Senior Product Designer",
    companyName: "Stripe",
    companyShort: "St",
    salary: "$140–185K",
    location: "🌎 Worldwide",
    tags: ["Remote", "Full-time"],
    category: "Design",
    description: "Shape the future of financial infrastructure. Own end-to-end design for core payment flows.",
    featured: true,
    logoColor: "linear-gradient(135deg,#1a6ef7,#7c3aed)",
    salaryMin: 140,
  },
  {
    _id: "2",
    title: "Staff Engineer — Platform",
    companyName: "Spotify",
    companyShort: "Sp",
    salary: "$210–270K",
    location: "🇸🇪 Stockholm",
    tags: ["Remote", "Full-time"],
    category: "Engineering",
    description: "Lead architecture decisions for Spotify's streaming infrastructure serving 600M users.",
    featured: false,
    logoColor: "linear-gradient(135deg,#059669,#06b6d4)",
    salaryMin: 210,
  },
  {
    _id: "3",
    title: "ML Engineer — Recommendations",
    companyName: "Netflix",
    companyShort: "N",
    salary: "$180–240K",
    location: "🇺🇸 Los Gatos",
    tags: ["Contract", "Remote"],
    category: "Data",
    description: "Build the algorithms that connect 260M viewers with content they love every night.",
    featured: true,
    logoColor: "linear-gradient(135deg,#dc2626,#ea580c)",
    salaryMin: 180,
  },
  {
    _id: "4",
    title: "Frontend Engineer",
    companyName: "Linear",
    companyShort: "Li",
    salary: "$130–160K",
    location: "🌎 Fully Remote",
    tags: ["Remote", "Full-time"],
    category: "Engineering",
    description: "Craft the fastest, most delightful project management experience ever built.",
    featured: false,
    logoColor: "linear-gradient(135deg,#7c3aed,#ec4899)",
    salaryMin: 130,
  },
  {
    _id: "5",
    title: "DevRel Engineer",
    companyName: "Vercel",
    companyShort: "Ve",
    salary: "$100–130K",
    location: "🌎 Worldwide",
    tags: ["Part-time", "Remote"],
    category: "Engineering",
    description: "Evangelize Next.js and the web platform to developers worldwide.",
    featured: false,
    logoColor: "linear-gradient(135deg,#0891b2,#1d4ed8)",
    salaryMin: 100,
  },
  {
    _id: "6",
    title: "Security Researcher",
    companyName: "Cloudflare",
    companyShort: "Cl",
    salary: "$155–195K",
    location: "🇺🇸 San Francisco",
    tags: ["Full-time"],
    category: "Security",
    description: "Protect the internet at scale. Investigate threats for 20% of all web traffic.",
    featured: true,
    logoColor: "linear-gradient(135deg,#b45309,#d97706)",
    salaryMin: 155,
  },
  {
    _id: "7",
    title: "Product Manager — Growth",
    companyName: "Figma",
    companyShort: "Fi",
    salary: "$145–190K",
    location: "🇺🇸 New York",
    tags: ["Full-time", "Remote"],
    category: "Product",
    description: "Drive activation and retention for Figma's 8M+ user base. Data-driven mindset required.",
    featured: false,
    logoColor: "linear-gradient(135deg,#ec4899,#8b5cf6)",
    salaryMin: 145,
  },
  {
    _id: "8",
    title: "Data Scientist",
    companyName: "Airbnb",
    companyShort: "Ab",
    salary: "$160–200K",
    location: "🇺🇸 San Francisco",
    tags: ["Full-time"],
    category: "Data",
    description: "Unlock insights that shape how 150M travellers find their next stay worldwide.",
    featured: false,
    logoColor: "linear-gradient(135deg,#ef4444,#f97316)",
    salaryMin: 160,
  },
  {
    _id: "9",
    title: "Brand Designer",
    companyName: "Notion",
    companyShort: "No",
    salary: "$110–145K",
    location: "🌎 Remote",
    tags: ["Remote", "Full-time"],
    category: "Design",
    description: "Define and evolve Notion's visual identity across every touchpoint, digital and physical.",
    featured: false,
    logoColor: "linear-gradient(135deg,#374151,#1f2937)",
    salaryMin: 110,
  },
  {
    _id: "10",
    title: "Growth Marketing Lead",
    companyName: "Loom",
    companyShort: "Lo",
    salary: "$95–130K",
    location: "🌎 Remote",
    tags: ["Remote", "Full-time"],
    category: "Marketing",
    description: "Own acquisition funnels and growth experiments for one of the fastest-growing SaaS tools.",
    featured: false,
    logoColor: "linear-gradient(135deg,#7c3aed,#4f46e5)",
    salaryMin: 95,
  },
];

export const COMPANIES: Company[] = [
  { name: "Google", short: "G", industry: "Tech", jobs: 2400, col: "linear-gradient(135deg,#1a6ef7,#7c3aed)" },
  { name: "Apple", short: "Ap", industry: "Tech", jobs: 1800, col: "linear-gradient(135deg,#374151,#1f2937)" },
  { name: "Amazon", short: "Am", industry: "Tech", jobs: 3100, col: "linear-gradient(135deg,#059669,#06b6d4)" },
  { name: "Meta", short: "Me", industry: "Tech", jobs: 900, col: "linear-gradient(135deg,#1d4ed8,#4f46e5)" },
  { name: "Netflix", short: "Nt", industry: "Media", jobs: 420, col: "linear-gradient(135deg,#dc2626,#ea580c)" },
  { name: "OpenAI", short: "Oa", industry: "Tech", jobs: 680, col: "linear-gradient(135deg,#0891b2,#1d4ed8)" },
  { name: "Stripe", short: "St", industry: "Finance", jobs: 540, col: "linear-gradient(135deg,#4f46e5,#7c3aed)" },
  { name: "Vercel", short: "Ve", industry: "Cloud", jobs: 120, col: "linear-gradient(135deg,#111,#444)" },
  { name: "Figma", short: "Fi", industry: "Tech", jobs: 210, col: "linear-gradient(135deg,#ec4899,#8b5cf6)" },
  { name: "Cloudflare", short: "Cf", industry: "Cloud", jobs: 380, col: "linear-gradient(135deg,#b45309,#d97706)" },
  { name: "Airbnb", short: "Ab", industry: "Tech", jobs: 290, col: "linear-gradient(135deg,#ef4444,#f97316)" },
  { name: "Notion", short: "No", industry: "Tech", jobs: 145, col: "linear-gradient(135deg,#374151,#6b7280)" },
];

export const CATEGORIES: Category[] = [
  { icon: "⚡", name: "Engineering", count: "41,200" },
  { icon: "🎨", name: "Design", count: "12,400" },
  { icon: "📊", name: "Data & AI", count: "18,900" },
  { icon: "🚀", name: "Product", count: "9,700" },
  { icon: "💼", name: "Marketing", count: "14,500" },
  { icon: "💰", name: "Finance", count: "7,800" },
  { icon: "🔒", name: "Security", count: "5,300" },
  { icon: "🌍", name: "Operations", count: "11,200" },
];
